version: '3.8'

services:
  frontend:
    build: ./client
    container_name: my-frontend-container
    ports:
      - "5173:5173"
    restart: always

  backend:
    build: ./api
    container_name: my-backend-container
    ports:
      - "5000:5000"
    restart: always
